---
- name: Create Ansible project structure on localhost
  hosts: localhost
  gather_facts: false

  vars_prompt:
    - name: "project_name"
      prompt: "Enter your project name"
      private: no
      default: "myproject"
      validate: '^[a-zA-Z][a-zA-Z0-9_-]*$'

  tasks:
    - name: Ensure project name is not empty
      fail:
        msg: "Project name cannot be empty"
      when: not project_name
      tags: 
        - validation
        - always

    - name: Create project directory structure
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ project_name }}"
        - "{{ project_name }}/inventory"
        - "{{ project_name }}/roles"
      tags:
        - directories
        - setup

    - name: Create inventory files
      copy:
        dest: "{{ project_name }}/inventory/{{ item }}"
        content: |
          # {{ item }} inventory file
          [all]
          # Add your hosts here
        mode: '0644'
      loop:
        - "production"
        - "staging"
        - "development"
      tags:
        - inventory
        - setup

    - name: Create project playbook file
      copy:
        dest: "{{ project_name }}/site.yml"
        content: |
          ---
          - name: Main playbook for {{ project_name }}
            hosts: all
            roles:
              - {{ project_name }}
        mode: '0644'
      tags:
        - playbook
        - setup

    - name: Create role directory structure
      file:
        path: "{{ project_name }}/roles/{{ project_name }}/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - defaults
        - files
        - handlers
        - meta
        - tasks
        - templates
        - vars
        - tests
      tags:
        - roles
        - directories
        - setup

    - name: Create main.yml files in role directories
      copy:
        dest: "{{ project_name }}/roles/{{ project_name }}/{{ item }}/main.yml"
        content: |
          {% if item == 'meta' %}
          galaxy_info:
            author: your_name
            description: Description of {{ project_name }} role
            license: MIT
            min_ansible_version: "2.9"
            platforms:
              - name: EL
                versions:
                  - all
              - name: Ubuntu
                versions:
                  - all
          dependencies: []
          {% else %}
          # {{ item }}/main.yml for {{ project_name }} role
          {% endif %}
        mode: '0644'
      loop:
        - defaults
        - handlers
        - meta
        - tasks
        - vars
      tags:
        - configuration
        - setup